// Generated by CoffeeScript 1.11.1
var cloneArgs, combine, isArray, isConstructor;

isConstructor = require("isConstructor");

cloneArgs = require("cloneArgs");

isArray = Array.isArray;

combine = function() {
  var dest, i, key, len, source, sources, value;
  sources = cloneArgs(arguments);
  dest = sources.shift();
  if (isArray(sources[0])) {
    sources = sources[0];
  }
  if (!isConstructor(dest, Object)) {
    return combine({}, sources);
  }
  for (i = 0, len = sources.length; i < len; i++) {
    source = sources[i];
    if (!source) {
      continue;
    }
    for (key in source) {
      value = source[key];
      if (value === void 0) {
        continue;
      }
      if (!isConstructor(value, Object)) {
        dest[key] = value;
      } else if (!isConstructor(dest[key], Object)) {
        dest[key] = combine({}, value);
      } else {
        combine(dest[key], value);
      }
    }
  }
  return dest;
};

module.exports = combine;
